#!/bin/bash
#
# onedc-nabers  This shell script takes care of starting and stopping
#               the onedc-nabers script.
#
# chkconfig: - 58 74
# description: onedc-nabers is the modbus daemon for ONEDC.

### BEGIN INIT INFO
# Provides: onedc-nabers
# Required-Start:  $network $local_fs
# Required-Stop: $network $local_fs
# Short-Description: start and stop onedc-nabers
# Description: onedc-nabers is the modbus daemon for ONEDC.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

prog=bms_adaptor
lockfile=/var/lock/subsys/$prog
datafile=/etc/sysconfig/$prog
user=obix

# Load the mandatory BMS config file
if [ -f $datafile ]; then
    . $datafile
else
    # Cannot start without data file. Exit
    echo "BMS data file not found. Exiting"
    exit 1
fi

start() {
        [ "$EUID" != "0" ] && exit 4
        [ "$NETWORKING" = "no" ] && exit 1
        [ -x /usr/bin/bms_adaptor ] || exit 5

        # Start daemons.
        echo -n $"Starting $prog: "
	daemon --user=$user $prog  $OPTIONS &
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}

stop() {
        [ "$EUID" != "0" ] && exit 4
        echo -n $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart|force-reload)
        stop
        start
        ;;
  try-restart|condrestart)
        if status $prog > /dev/null; then
            stop
            start
        fi
        ;;
  reload)
        exit 3
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
        exit 2
esac

