#! /bin/sh -
#
# A simple shell script to test History.Append facility to append
# one single history record to the specified device.
#
# Copyright (c) 2013-2015 Qingtao Cao
#

usage()
{
	cat<<EOF
usage:
	$0 	< -d "device href segment" > < -s "timestamp" >
		[ -e "kWh" ] [ -p "kW" ] [-v "voltage"]
		[ -i "current_intensity" ]
Where
	-d The href segment of the device, e.g., "/M1/DH1/BCM01/CB01/"
	-s The start timestamp, as in format '$(date +%FT%T)'
	-e Total energy consumption
	-p Power load
	-v Voltage
	-i Current intensity

EOF
}

device= timestamp=

current_intensity="0.000000"
voltage="230.000000"
energy="0.000000"
power="0.000000"

while getopts :d:s:i:v:p:e: opt
do
	case $opt in
	d)	device=$OPTARG
		;;
	s)	timestamp=$OPTARG
		;;
	i)	current_intensity=$OPTARG
		;;
	v)	voltage=$OPTARG
		;;
	e)	energy=$OPTARG
		;;
	p)	power=$OPTARG
		;;
	esac
done

shift $((OPTIND - 1))

if [ -z "$device" -o -z "$timestamp" ]; then
	usage
	exit
fi

# Discard the potential history lobby URI and preceding and following slash
device=${device#/obix/historyService/histories/}
device=${device#/}
device=${device%/}

curl $verbose -XPOST --data "
<obj is=\"obix:historyAppendIn\">
	<list name=\"data\" of=\"obix:HistoryRecord\">
		<obj is=\"obix:HistoryRecord\">
			<abstime name=\"timestamp\" val=\"$timestamp\"/>
			<real name=\"kWh\" val=\"$energy\"/>
			<real name=\"kW\" val=\"$power\"/>
			<real name=\"V\" val=\"$voltage\"/>
			<real name=\"PF\" val=\"0.900000\"/>
			<real name=\"I\" val=\"$current_intensity\"/>
		</obj>
	</list>
</obj>" \
http://localhost/obix/historyService/histories/$device/append

echo
