#!/bin/bash -

##############################################################################
# Copyright (c) 2013-2014 NEXTDC LTD.
#
# This file is part of oBIX.
#
# oBIX is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# oBIX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with oBIX.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

# if you pass an argument to this script it will be prepended to the 
# location of the xml file, see ${1} below in curl command

curl -XPOST --data "@${1}example_device.xml" http://localhost/obix/signUp | grep err 
RETVAL=$?

# If grep found err in output then we have an error, and exit test script with 1
if [ $RETVAL -eq 0 ]; then
	exit 1
else
	exit 0
fi

exit 0

