#! /bin/sh -
#
# A simple shell script to delete all watch objects
#
# Copyright (c) 2013-2015 Qingtao Cao
#

for i in `curl http://localhost/obix/watchService | \
		  xmllint --format - | \
		  grep LongPollWatch | \
		  awk -F 'href="watch' '{print $2}' | \
		  awk -F '"' '{print $1}'`; do \
	./watchDeleteSingle -w $i > null 2>&1; \
done
