#! /bin/sh -
#
# A simple shell script to test Watch.pollChange facility
#
# Qingtao Cao <qingtao.cao@nextdc.com>
#

usage()
{
	cat << EOF
usage:
	$0 [ -v ] < -w "watch ID" >
Where
	-v Verbose mode
	-w ID of the watch to be polled
EOF
}

verbose= watch=

while getopts :vw: opt
do
	case $opt in
	w)	watch=$OPTARG
		;;
	v)	verbose="-v"
		;;
	esac
done

shift $((OPTIND - 1))

if [ -z "$watch" ]
then
	usage
	exit
fi

setsize=64
folder=`expr $watch / $setsize`

# No quotation marks around $verbose or otherwise curl
# will complain about malformed URL if it is empty

curl $verbose -XPOST --data '' http://localhost:4242/obix/watchService/$folder/watch$watch/pollChanges
