#! /bin/sh -
#
# A simple shell script to delete one single watch object
#
# Copyright (c) 2013-2015 Qingtao Cao
#

usage()
{
	cat << EOF
usage:
	$0 [ -v ] < -w "watch ID" >
Where
	-v Verbose mode
	-w ID of the watch to be deleted
EOF
}

verbose= watch=

while getopts :vw: opt
do
	case $opt in
	w)	watch=$OPTARG
		;;
	v)	verbose="-v"
		;;
	esac
done

shift $((OPTIND - 1))

if [ -z "$watch" ]
then
	usage
	exit
fi

# 64 is the maximal number of watch objects in one sub-folder under
# watchService/ adopted in watch implementation. This 2-level hierarchy
# is used to avoid having all watches under one same parent folder of
# watchService so as to cut down the potential overhead of xml_find_child.
setsize=64
folder=`expr $watch / $setsize`

# No quotation marks around $verbose or otherwise curl
# will complain about malformed URL if it is empty

curl $verbose -XPOST --data '' http://localhost/obix/watchService/$folder/watch$watch/delete
